# Generated by Django 4.2.3 on 2023-08-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_date_creation_category_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
