# Generated by Django 4.2.4 on 2023-09-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_detsale_prod_sale_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='prod',
        ),
    ]
