# Generated by Django 4.2.4 on 2023-09-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_sale_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
            preserve_default=False,
        ),
    ]
