# Generated by Django 4.2.4 on 2023-09-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_detsale_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
    ]
