# Generated by Django 4.2.4 on 2023-09-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_detsale_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
            preserve_default=False,
        ),
    ]
